export const COUNTRIES = [
    {
        name: "Afghanistan",
        code: "AF",
        timezone: "Afghanistan Standard Time",
        utc: "UTC+04:30",
        mobileCode: "+93",
        image: "🇦🇫",
    },
    {
        name: "Åland Islands",
        code: "AX",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+35818",
        image: "🇦🇽",
    },
    {
        name: "Albania",
        code: "AL",
        timezone: "Central Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+355",
        image: "🇦🇱",
    },
    {
        name: "Algeria",
        code: "DZ",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+213",
        image: "🇩🇿",
    },
    {
        name: "American Samoa",
        code: "AS",
        timezone: "UTC-11",
        utc: "UTC-11:00",
        mobileCode: "+1684",
        image: "🇦🇸",
    },
    {
        name: "Andorra",
        code: "AD",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+376",
        image: "🇦🇩",
    },
    {
        name: "Angola",
        code: "AO",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+244",
        image: "🇦🇴",
    },
    {
        name: "Anguilla",
        code: "AI",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1264",
        image: "🇦🇮",
    },
    // {
    //     "name": "Antarctica",
    //     "code": "AQ",
    //     "timezone": "Pacific SA Standard Time",
    //     "utc": "UTC-03:00",
    //     "mobileCode": "+",
    //     "image": "🇦🇶"
    // },
    {
        name: "Antigua and Barbuda",
        code: "AG",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1268",
        image: "🇦🇬",
    },
    {
        name: "Argentina",
        code: "AR",
        timezone: "Argentina Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+54",
        image: "🇦🇷",
    },
    {
        name: "Armenia",
        code: "AM",
        timezone: "Caucasus Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+374",
        image: "🇦🇲",
    },
    {
        name: "Aruba",
        code: "AW",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+297",
        image: "🇦🇼",
    },
    {
        name: "Australia",
        code: "AU",
        timezone: "AUS Eastern Standard Time",
        utc: "UTC+10:00",
        mobileCode: "+61",
        image: "🇦🇺",
    },
    {
        name: "Austria",
        code: "AT",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+43",
        image: "🇦🇹",
    },
    {
        name: "Azerbaijan",
        code: "AZ",
        timezone: "Azerbaijan Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+994",
        image: "🇦🇿",
    },
    {
        name: "Bahamas, The",
        code: "BS",
        timezone: "Eastern Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+1242",
        image: "🇧🇸",
    },
    {
        name: "Bahrain",
        code: "BH",
        timezone: "Arab Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+973",
        image: "🇧🇭",
    },
    {
        name: "Bangladesh",
        code: "BD",
        timezone: "Bangladesh Standard Time",
        utc: "UTC+06:00",
        mobileCode: "+880",
        image: "🇧🇩",
    },
    {
        name: "Barbados",
        code: "BB",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1246",
        image: "🇧🇧",
    },
    {
        name: "Belarus",
        code: "BY",
        timezone: "Belarus Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+375",
        image: "🇧🇾",
    },
    {
        name: "Belgium",
        code: "BE",
        timezone: "Romance Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+32",
        image: "🇧🇪",
    },
    {
        name: "Belize",
        code: "BZ",
        timezone: "Central America Standard Time",
        utc: "UTC-06:00",
        mobileCode: "+501",
        image: "🇧🇿",
    },
    {
        name: "Benin",
        code: "BJ",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+229",
        image: "🇧🇯",
    },
    {
        name: "Bermuda",
        code: "BM",
        timezone: "Atlantic Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1441",
        image: "🇧🇲",
    },
    {
        name: "Bhutan",
        code: "BT",
        timezone: "Bangladesh Standard Time",
        utc: "UTC+06:00",
        mobileCode: "+975",
        image: "🇧🇹",
    },
    {
        name: "Bolivarian Republic of Venezuela",
        code: "VE",
        timezone: "Venezuela Standard Time",
        utc: "UTC-04:30",
        mobileCode: "+58",
        image: "🇻🇪",
    },
    {
        name: "Bolivia",
        code: "BO",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+591",
        image: "🇧🇴",
    },
    {
        name: "Bonaire, Sint Eustatius and Saba",
        code: "BQ",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+599",
        image: "🇧🇶",
    },
    {
        name: "Bosnia and Herzegovina",
        code: "BA",
        timezone: "Central European Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+387",
        image: "🇧🇦",
    },
    {
        name: "Botswana",
        code: "BW",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+267",
        image: "🇧🇼",
    },
    // {
    //     "name": "Bouvet Island",
    //     "code": "BV",
    //     "timezone": "UTC",
    //     "utc": "UTC",
    //     "mobileCode": "+",
    //     "image": "🇧🇻"
    // },
    {
        name: "Brazil",
        code: "BR",
        timezone: "E. South America Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+55",
        image: "🇧🇷",
    },
    {
        name: "British Indian Ocean Territory",
        code: "IO",
        timezone: "Central Asia Standard Time",
        utc: "UTC+06:00",
        mobileCode: "+246",
        image: "🇮🇴",
    },
    {
        name: "Brunei",
        code: "BN",
        timezone: "Singapore Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+673",
        image: "🇧🇳",
    },
    {
        name: "Bulgaria",
        code: "BG",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+359",
        image: "🇧🇬",
    },
    {
        name: "Burkina Faso",
        code: "BF",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+226",
        image: "🇧🇫",
    },
    {
        name: "Burundi",
        code: "BI",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+257",
        image: "🇧🇮",
    },
    {
        name: "Cabo Verde",
        code: "CV",
        timezone: "Cape Verde Standard Time",
        utc: "UTC-01:00",
        mobileCode: "+238",
        image: "🇨🇻",
    },
    {
        name: "Cambodia",
        code: "KH",
        timezone: "SE Asia Standard Time",
        utc: "UTC+07:00",
        mobileCode: "+855",
        image: "🇰🇭",
    },
    {
        name: "Cameroon",
        code: "CM",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+237",
        image: "🇨🇲",
    },
    {
        name: "Canada",
        code: "CA",
        timezone: "Eastern Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+1",
        image: "🇨🇦",
    },
    {
        name: "Cayman Islands",
        code: "KY",
        timezone: "SA Pacific Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+1345",
        image: "🇰🇾",
    },
    {
        name: "Central African Republic",
        code: "CF",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+236",
        image: "🇨🇫",
    },
    {
        name: "Chad",
        code: "TD",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+235",
        image: "🇹🇩",
    },
    {
        name: "Chile",
        code: "CL",
        timezone: "Pacific SA Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+56",
        image: "🇨🇱",
    },
    {
        name: "China",
        code: "CN",
        timezone: "China Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+86",
        image: "🇨🇳",
    },
    {
        name: "Christmas Island",
        code: "CX",
        timezone: "SE Asia Standard Time",
        utc: "UTC+07:00",
        mobileCode: "+61",
        image: "🇨🇽",
    },
    {
        name: "Cocos (Keeling) Islands",
        code: "CC",
        timezone: "Myanmar Standard Time",
        utc: "UTC+06:30",
        mobileCode: "+61",
        image: "🇨🇨",
    },
    {
        name: "Colombia",
        code: "CO",
        timezone: "SA Pacific Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+57",
        image: "🇨🇴",
    },
    {
        name: "Comoros",
        code: "KM",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+269",
        image: "🇰🇲",
    },
    {
        name: "Congo",
        code: "CG",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+242",
        image: "🇨🇬",
    },
    {
        name: "Congo (DRC)",
        code: "CD",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+243",
        image: "🇨🇩",
    },
    {
        name: "Cook Islands",
        code: "CK",
        timezone: "Hawaiian Standard Time",
        utc: "UTC-10:00",
        mobileCode: "+682",
        image: "🇨🇰",
    },
    {
        name: "Costa Rica",
        code: "CR",
        timezone: "Central America Standard Time",
        utc: "UTC-06:00",
        mobileCode: "+506",
        image: "🇨🇷",
    },
    {
        name: "Côte d'Ivoire",
        code: "CI",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+225",
        image: "🇨🇮",
    },
    {
        name: "Croatia",
        code: "HR",
        timezone: "Central European Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+385",
        image: "🇭🇷",
    },
    {
        name: "Cuba",
        code: "CU",
        timezone: "Eastern Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+53",
        image: "🇨🇺",
    },
    {
        name: "Curaçao",
        code: "CW",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+599",
        image: "🇨🇼",
    },
    {
        name: "Cyprus",
        code: "CY",
        timezone: "E. Europe Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+357",
        image: "🇨🇾",
    },
    {
        name: "Czech Republic",
        code: "CZ",
        timezone: "Central Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+420",
        image: "🇨🇿",
    },
    {
        name: "Democratic Republic of Timor-Leste",
        code: "TL",
        timezone: "Tokyo Standard Time",
        utc: "UTC+09:00",
        mobileCode: "+670",
        image: "🇹🇱",
    },
    {
        name: "Denmark",
        code: "DK",
        timezone: "Romance Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+45",
        image: "🇩🇰",
    },
    {
        name: "Djibouti",
        code: "DJ",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+253",
        image: "🇩🇯",
    },
    {
        name: "Dominica",
        code: "DM",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1767",
        image: "🇩🇲",
    },
    {
        name: "Dominican Republic",
        code: "DO",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1809",
        image: "🇩🇴",
    },
    {
        name: "Ecuador",
        code: "EC",
        timezone: "SA Pacific Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+593",
        image: "🇪🇨",
    },
    {
        name: "Egypt",
        code: "EG",
        timezone: "Egypt Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+20",
        image: "🇪🇬",
    },
    {
        name: "El Salvador",
        code: "SV",
        timezone: "Central America Standard Time",
        utc: "UTC-06:00",
        mobileCode: "+503",
        image: "🇸🇻",
    },
    {
        name: "Equatorial Guinea",
        code: "GQ",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+240",
        image: "🇬🇶",
    },
    {
        name: "Eritrea",
        code: "ER",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+291",
        image: "🇪🇷",
    },
    {
        name: "Estonia",
        code: "EE",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+372",
        image: "🇪🇪",
    },
    {
        name: "Ethiopia",
        code: "ET",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+251",
        image: "🇪🇹",
    },
    {
        name: "Falkland Islands (Islas Malvinas)",
        code: "FK",
        timezone: "SA Eastern Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+500",
        image: "🇫🇰",
    },
    {
        name: "Faroe Islands",
        code: "FO",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+298",
        image: "🇫🇴",
    },
    {
        name: "Fiji Islands",
        code: "FJ",
        timezone: "Fiji Standard Time",
        utc: "UTC+12:00",
        mobileCode: "+679",
        image: "🇫🇯",
    },
    {
        name: "Finland",
        code: "FI",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+358",
        image: "🇫🇮",
    },
    {
        name: "France",
        code: "FR",
        timezone: "Romance Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+33",
        image: "🇫🇷",
    },
    {
        name: "French Guiana",
        code: "GF",
        timezone: "SA Eastern Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+594",
        image: "🇬🇫",
    },
    {
        name: "French Polynesia",
        code: "PF",
        timezone: "Hawaiian Standard Time",
        utc: "UTC-10:00",
        mobileCode: "+689",
        image: "🇵🇫",
    },
    // {
    //     "name": "French Southern and Antarctic Lands",
    //     "code": "TF",
    //     "timezone": "West Asia Standard Time",
    //     "utc": "UTC+05:00",
    //     "mobileCode": "+",
    //     "image": "🇹🇫"
    // },
    {
        name: "Gabon",
        code: "GA",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+241",
        image: "🇬🇦",
    },
    {
        name: "Gambia, The",
        code: "GM",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+220",
        image: "🇬🇲",
    },
    {
        name: "Georgia",
        code: "GE",
        timezone: "Georgian Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+995",
        image: "🇬🇪",
    },
    {
        name: "Germany",
        code: "DE",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+49",
        image: "🇩🇪",
    },
    {
        name: "Ghana",
        code: "GH",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+233",
        image: "🇬🇭",
    },
    {
        name: "Gibraltar",
        code: "GI",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+350",
        image: "🇬🇮",
    },
    {
        name: "Greece",
        code: "GR",
        timezone: "GTB Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+30",
        image: "🇬🇷",
    },
    {
        name: "Greenland",
        code: "GL",
        timezone: "Greenland Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+299",
        image: "🇬🇱",
    },
    {
        name: "Grenada",
        code: "GD",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1473",
        image: "🇬🇩",
    },
    {
        name: "Guadeloupe",
        code: "GP",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+590",
        image: "🇬🇵",
    },
    {
        name: "Guam",
        code: "GU",
        timezone: "West Pacific Standard Time",
        utc: "UTC+10:00",
        mobileCode: "+1671",
        image: "🇬🇺",
    },
    {
        name: "Guatemala",
        code: "GT",
        timezone: "Central America Standard Time",
        utc: "UTC-06:00",
        mobileCode: "+502",
        image: "🇬🇹",
    },
    {
        name: "Guernsey",
        code: "GG",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+441481",
        image: "🇬🇬",
    },
    {
        name: "Guinea",
        code: "GN",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+224",
        image: "🇬🇳",
    },
    {
        name: "Guinea-Bissau",
        code: "GW",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+245",
        image: "🇬🇼",
    },
    {
        name: "Guyana",
        code: "GY",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+592",
        image: "🇬🇾",
    },
    {
        name: "Haiti",
        code: "HT",
        timezone: "Eastern Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+509",
        image: "🇭🇹",
    },
    // {
    //     "name": "Heard Island and McDonald Islands",
    //     "code": "HM",
    //     "timezone": "Mauritius Standard Time",
    //     "utc": "UTC+04:00",
    //     "mobileCode": "+ ",
    //     "image": "🇭🇲"
    // },
    {
        name: "Honduras",
        code: "HN",
        timezone: "Central America Standard Time",
        utc: "UTC-06:00",
        mobileCode: "+504",
        image: "🇭🇳",
    },
    {
        name: "Hong Kong SAR",
        code: "HK",
        timezone: "China Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+852",
        image: "🇭🇰",
    },
    {
        name: "Hungary",
        code: "HU",
        timezone: "Central Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+36",
        image: "🇭🇺",
    },
    {
        name: "Iceland",
        code: "IS",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+354",
        image: "🇮🇸",
    },
    {
        name: "India",
        code: "IN",
        timezone: "India Standard Time",
        utc: "UTC+05:30",
        mobileCode: "+91",
        image: "🇮🇳",
    },
    {
        name: "Indonesia",
        code: "ID",
        timezone: "SE Asia Standard Time",
        utc: "UTC+07:00",
        mobileCode: "+62",
        image: "🇮🇩",
    },
    {
        name: "Iran",
        code: "IR",
        timezone: "Iran Standard Time",
        utc: "UTC+03:30",
        mobileCode: "+98",
        image: "🇮🇷",
    },
    {
        name: "Iraq",
        code: "IQ",
        timezone: "Arabic Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+964",
        image: "🇮🇶",
    },
    {
        name: "Ireland",
        code: "IE",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+353",
        image: "🇮🇪",
    },
    {
        name: "Israel",
        code: "IL",
        timezone: "Israel Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+972",
        image: "🇮🇱",
    },
    {
        name: "Italy",
        code: "IT",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+39",
        image: "🇮🇹",
    },
    {
        name: "Jamaica",
        code: "JM",
        timezone: "SA Pacific Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+1876",
        image: "🇯🇲",
    },
    {
        name: "Jan Mayen",
        code: "SJ",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+47",
        image: "🇸🇯",
    },
    {
        name: "Japan",
        code: "JP",
        timezone: "Tokyo Standard Time",
        utc: "UTC+09:00",
        mobileCode: "+81",
        image: "🇯🇵",
    },
    {
        name: "Jersey",
        code: "JE",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+441534",
        image: "🇯🇪",
    },
    {
        name: "Jordan",
        code: "JO",
        timezone: "Jordan Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+962",
        image: "🇯🇴",
    },
    {
        name: "Kazakhstan",
        code: "KZ",
        timezone: "Central Asia Standard Time",
        utc: "UTC+06:00",
        mobileCode: "+7",
        image: "🇰🇿",
    },
    {
        name: "Kenya",
        code: "KE",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+254",
        image: "🇰🇪",
    },
    {
        name: "Kiribati",
        code: "KI",
        timezone: "UTC+12",
        utc: "UTC+12:00",
        mobileCode: "+686",
        image: "🇰🇮",
    },
    {
        name: "Korea",
        code: "KR",
        timezone: "Korea Standard Time",
        utc: "UTC+09:00",
        mobileCode: "+82",
        image: "🇰🇷",
    },
    // {
    //     "name": "Kosovo",
    //     "code": "XK",
    //     "timezone": "Central European Standard Time",
    //     "utc": "UTC+01:00",
    //     "mobileCode": "+",
    //     "image": "🇽🇰"
    // },
    {
        name: "Kuwait",
        code: "KW",
        timezone: "Arab Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+965",
        image: "🇰🇼",
    },
    {
        name: "Kyrgyzstan",
        code: "KG",
        timezone: "Central Asia Standard Time",
        utc: "UTC+06:00",
        mobileCode: "+996",
        image: "🇰🇬",
    },
    {
        name: "Laos",
        code: "LA",
        timezone: "SE Asia Standard Time",
        utc: "UTC+07:00",
        mobileCode: "+856",
        image: "🇱🇦",
    },
    {
        name: "Latvia",
        code: "LV",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+371",
        image: "🇱🇻",
    },
    {
        name: "Lebanon",
        code: "LB",
        timezone: "Middle East Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+961",
        image: "🇱🇧",
    },
    {
        name: "Lesotho",
        code: "LS",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+266",
        image: "🇱🇸",
    },
    {
        name: "Liberia",
        code: "LR",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+231",
        image: "🇱🇷",
    },
    {
        name: "Libya",
        code: "LY",
        timezone: "E. Europe Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+218",
        image: "🇱🇾",
    },
    {
        name: "Liechtenstein",
        code: "LI",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+423",
        image: "🇱🇮",
    },
    {
        name: "Lithuania",
        code: "LT",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+370",
        image: "🇱🇹",
    },
    {
        name: "Luxembourg",
        code: "LU",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+352",
        image: "🇱🇺",
    },
    {
        name: "Macao SAR",
        code: "MO",
        timezone: "China Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+853",
        image: "🇲🇴",
    },
    {
        name: "Macedonia, Former Yugoslav Republic of",
        code: "MK",
        timezone: "Central European Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+389",
        image: "🇲🇰",
    },
    {
        name: "Madagascar",
        code: "MG",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+261",
        image: "🇲🇬",
    },
    {
        name: "Malawi",
        code: "MW",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+265",
        image: "🇲🇼",
    },
    {
        name: "Malaysia",
        code: "MY",
        timezone: "Singapore Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+60",
        image: "🇲🇾",
    },
    {
        name: "Maldives",
        code: "MV",
        timezone: "West Asia Standard Time",
        utc: "UTC+05:00",
        mobileCode: "+960",
        image: "🇲🇻",
    },
    {
        name: "Mali",
        code: "ML",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+223",
        image: "🇲🇱",
    },
    {
        name: "Malta",
        code: "MT",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+356",
        image: "🇲🇹",
    },
    {
        name: "Man, Isle of",
        code: "IM",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+441624",
        image: "🇮🇲",
    },
    {
        name: "Marshall Islands",
        code: "MH",
        timezone: "UTC+12",
        utc: "UTC+12:00",
        mobileCode: "+692",
        image: "🇲🇭",
    },
    {
        name: "Martinique",
        code: "MQ",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+596",
        image: "🇲🇶",
    },
    {
        name: "Mauritania",
        code: "MR",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+222",
        image: "🇲🇷",
    },
    {
        name: "Mauritius",
        code: "MU",
        timezone: "Mauritius Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+230",
        image: "🇲🇺",
    },
    {
        name: "Mayotte",
        code: "YT",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+262",
        image: "🇾🇹",
    },
    {
        name: "Mexico",
        code: "MX",
        timezone: "Central Standard Time (Mexico)",
        utc: "UTC-06:00",
        mobileCode: "+52",
        image: "🇲🇽",
    },
    {
        name: "Micronesia",
        code: "FM",
        timezone: "West Pacific Standard Time",
        utc: "UTC+10:00",
        mobileCode: "+691",
        image: "🇫🇲",
    },
    {
        name: "Moldova",
        code: "MD",
        timezone: "GTB Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+373",
        image: "🇲🇩",
    },
    {
        name: "Monaco",
        code: "MC",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+377",
        image: "🇲🇨",
    },
    {
        name: "Mongolia",
        code: "MN",
        timezone: "Ulaanbaatar Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+976",
        image: "🇲🇳",
    },
    {
        name: "Montenegro",
        code: "ME",
        timezone: "Central European Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+382",
        image: "🇲🇪",
    },
    {
        name: "Montserrat",
        code: "MS",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1664",
        image: "🇲🇸",
    },
    {
        name: "Morocco",
        code: "MA",
        timezone: "Morocco Standard Time",
        utc: "UTC",
        mobileCode: "+212",
        image: "🇲🇦",
    },
    {
        name: "Mozambique",
        code: "MZ",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+258",
        image: "🇲🇿",
    },
    {
        name: "Myanmar",
        code: "MM",
        timezone: "Myanmar Standard Time",
        utc: "UTC+06:30",
        mobileCode: "+95",
        image: "🇲🇲",
    },
    {
        name: "Namibia",
        code: "NA",
        timezone: "Namibia Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+264",
        image: "🇳🇦",
    },
    {
        name: "Nauru",
        code: "NR",
        timezone: "UTC+12",
        utc: "UTC+12:00",
        mobileCode: "+674",
        image: "🇳🇷",
    },
    {
        name: "Nepal",
        code: "NP",
        timezone: "Nepal Standard Time",
        utc: "UTC+05:45",
        mobileCode: "+977",
        image: "🇳🇵",
    },
    {
        name: "Netherlands",
        code: "NL",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+31",
        image: "🇳🇱",
    },
    {
        name: "New Caledonia",
        code: "NC",
        timezone: "Central Pacific Standard Time",
        utc: "UTC+11:00",
        mobileCode: "+687",
        image: "🇳🇨",
    },
    {
        name: "New Zealand",
        code: "NZ",
        timezone: "New Zealand Standard Time",
        utc: "UTC+12:00",
        mobileCode: "+64",
        image: "🇳🇿",
    },
    {
        name: "Nicaragua",
        code: "NI",
        timezone: "Central America Standard Time",
        utc: "UTC-06:00",
        mobileCode: "+505",
        image: "🇳🇮",
    },
    {
        name: "Niger",
        code: "NE",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+227",
        image: "🇳🇪",
    },
    {
        name: "Nigeria",
        code: "NG",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+234",
        image: "🇳🇬",
    },
    {
        name: "Niue",
        code: "NU",
        timezone: "UTC-11",
        utc: "UTC-11:00",
        mobileCode: "+683",
        image: "🇳🇺",
    },
    {
        name: "Norfolk Island",
        code: "NF",
        timezone: "Central Pacific Standard Time",
        utc: "UTC+11:00",
        mobileCode: "+672",
        image: "🇳🇫",
    },
    {
        name: "North Korea",
        code: "KP",
        timezone: "Korea Standard Time",
        utc: "UTC+09:00",
        mobileCode: "+850",
        image: "🇰🇵",
    },
    {
        name: "Northern Mariana Islands",
        code: "MP",
        timezone: "West Pacific Standard Time",
        utc: "UTC+10:00",
        mobileCode: "+1670",
        image: "🇲🇵",
    },
    {
        name: "Norway",
        code: "NO",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+47",
        image: "🇳🇴",
    },
    {
        name: "Oman",
        code: "OM",
        timezone: "Arabian Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+968",
        image: "🇴🇲",
    },
    {
        name: "Pakistan",
        code: "PK",
        timezone: "Pakistan Standard Time",
        utc: "UTC+05:00",
        mobileCode: "+92",
        image: "🇵🇰",
    },
    {
        name: "Palau",
        code: "PW",
        timezone: "Tokyo Standard Time",
        utc: "UTC+09:00",
        mobileCode: "+680",
        image: "🇵🇼",
    },
    {
        name: "Palestinian Authority",
        code: "PS",
        timezone: "Egypt Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+970",
        image: "🇵🇸",
    },
    {
        name: "Panama",
        code: "PA",
        timezone: "SA Pacific Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+507",
        image: "🇵🇦",
    },
    {
        name: "Papua New Guinea",
        code: "PG",
        timezone: "West Pacific Standard Time",
        utc: "UTC+10:00",
        mobileCode: "+675",
        image: "🇵🇬",
    },
    {
        name: "Paraguay",
        code: "PY",
        timezone: "Paraguay Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+595",
        image: "🇵🇾",
    },
    {
        name: "Peru",
        code: "PE",
        timezone: "SA Pacific Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+51",
        image: "🇵🇪",
    },
    {
        name: "Philippines",
        code: "PH",
        timezone: "Singapore Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+63",
        image: "🇵🇭",
    },
    {
        name: "Pitcairn Islands",
        code: "PN",
        timezone: "Pacific Standard Time",
        utc: "UTC-08:00",
        mobileCode: "+870",
        image: "🇵🇳",
    },
    {
        name: "Poland",
        code: "PL",
        timezone: "Central European Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+48",
        image: "🇵🇱",
    },
    {
        name: "Portugal",
        code: "PT",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+351",
        image: "🇵🇹",
    },
    {
        name: "Puerto Rico",
        code: "PR",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1787",
        image: "🇵🇷",
    },
    {
        name: "Qatar",
        code: "QA",
        timezone: "Arab Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+974",
        image: "🇶🇦",
    },
    {
        name: "Reunion",
        code: "RE",
        timezone: "Mauritius Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+262",
        image: "🇷🇪",
    },
    {
        name: "Romania",
        code: "RO",
        timezone: "GTB Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+40",
        image: "🇷🇴",
    },
    {
        name: "Russia",
        code: "RU",
        timezone: "Russian Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+7",
        image: "🇷🇺",
    },
    {
        name: "Rwanda",
        code: "RW",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+250",
        image: "🇷🇼",
    },
    {
        name: "Saint Barthélemy",
        code: "BL",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+590",
        image: "🇧🇱",
    },
    {
        name: "Saint Helena, Ascension and Tristan da Cunha",
        code: "SH",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+290",
        image: "🇸🇭",
    },
    {
        name: "Saint Kitts and Nevis",
        code: "KN",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1869",
        image: "🇰🇳",
    },
    {
        name: "Saint Lucia",
        code: "LC",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1758",
        image: "🇱🇨",
    },
    {
        name: "Saint Martin (French part)",
        code: "MF",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+590",
        image: "🇲🇫",
    },
    {
        name: "Saint Pierre and Miquelon",
        code: "PM",
        timezone: "Greenland Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+508",
        image: "🇵🇲",
    },
    {
        name: "Saint Vincent and the Grenadines",
        code: "VC",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1784",
        image: "🇻🇨",
    },
    {
        name: "Samoa",
        code: "WS",
        timezone: "Samoa Standard Time",
        utc: "UTC+13:00",
        mobileCode: "+685",
        image: "🇼🇸",
    },
    {
        name: "San Marino",
        code: "SM",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+378",
        image: "🇸🇲",
    },
    {
        name: "São Tomé and Príncipe",
        code: "ST",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+239",
        image: "🇸🇹",
    },
    {
        name: "Saudi Arabia",
        code: "SA",
        timezone: "Arab Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+966",
        image: "🇸🇦",
    },
    {
        name: "Senegal",
        code: "SN",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+221",
        image: "🇸🇳",
    },
    {
        name: "Serbia",
        code: "RS",
        timezone: "Central Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+381",
        image: "🇷🇸",
    },
    {
        name: "Seychelles",
        code: "SC",
        timezone: "Mauritius Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+248",
        image: "🇸🇨",
    },
    {
        name: "Sierra Leone",
        code: "SL",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+232",
        image: "🇸🇱",
    },
    {
        name: "Singapore",
        code: "SG",
        timezone: "Singapore Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+65",
        image: "🇸🇬",
    },
    {
        name: "Sint Maarten (Dutch part)",
        code: "SX",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+599",
        image: "🇸🇽",
    },
    {
        name: "Slovakia",
        code: "SK",
        timezone: "Central Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+421",
        image: "🇸🇰",
    },
    {
        name: "Slovenia",
        code: "SI",
        timezone: "Central Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+386",
        image: "🇸🇮",
    },
    {
        name: "Solomon Islands",
        code: "SB",
        timezone: "Central Pacific Standard Time",
        utc: "UTC+11:00",
        mobileCode: "+677",
        image: "🇸🇧",
    },
    {
        name: "Somalia",
        code: "SO",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+252",
        image: "🇸🇴",
    },
    {
        name: "South Africa",
        code: "ZA",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+27",
        image: "🇿🇦",
    },
    // {
    //     "name": "South Georgia and the South Sandwich Islands",
    //     "code": "GS",
    //     "timezone": "UTC-02",
    //     "utc": "UTC-02:00",
    //     "mobileCode": "+",
    //     "image": "🇬🇸"
    // },
    {
        name: "South Sudan",
        code: "SS",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+211",
        image: "🇸🇸",
    },
    {
        name: "Spain",
        code: "ES",
        timezone: "Romance Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+34",
        image: "🇪🇸",
    },
    {
        name: "Sri Lanka",
        code: "LK",
        timezone: "Sri Lanka Standard Time",
        utc: "UTC+05:30",
        mobileCode: "+94",
        image: "🇱🇰",
    },
    {
        name: "Sudan",
        code: "SD",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+249",
        image: "🇸🇩",
    },
    {
        name: "Suriname",
        code: "SR",
        timezone: "SA Eastern Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+597",
        image: "🇸🇷",
    },
    {
        name: "Svalbard",
        code: "SJ",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+47",
        image: "🇸🇯",
    },
    {
        name: "Swaziland",
        code: "SZ",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+268",
        image: "🇸🇿",
    },
    {
        name: "Sweden",
        code: "SE",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+46",
        image: "🇸🇪",
    },
    {
        name: "Switzerland",
        code: "CH",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+41",
        image: "🇨🇭",
    },
    {
        name: "Syria",
        code: "SY",
        timezone: "Syria Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+963",
        image: "🇸🇾",
    },
    {
        name: "Taiwan",
        code: "TW",
        timezone: "Taipei Standard Time",
        utc: "UTC+08:00",
        mobileCode: "+886",
        image: "🇹🇼",
    },
    {
        name: "Tajikistan",
        code: "TJ",
        timezone: "West Asia Standard Time",
        utc: "UTC+05:00",
        mobileCode: "+992",
        image: "🇹🇯",
    },
    {
        name: "Tanzania",
        code: "TZ",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+255",
        image: "🇹🇿",
    },
    {
        name: "Thailand",
        code: "TH",
        timezone: "SE Asia Standard Time",
        utc: "UTC+07:00",
        mobileCode: "+66",
        image: "🇹🇭",
    },
    {
        name: "Togo",
        code: "TG",
        timezone: "Greenwich Standard Time",
        utc: "UTC",
        mobileCode: "+228",
        image: "🇹🇬",
    },
    {
        name: "Tokelau",
        code: "TK",
        timezone: "Tonga Standard Time",
        utc: "UTC+13:00",
        mobileCode: "+690",
        image: "🇹🇰",
    },
    {
        name: "Tonga",
        code: "TO",
        timezone: "Tonga Standard Time",
        utc: "UTC+13:00",
        mobileCode: "+676",
        image: "🇹🇴",
    },
    {
        name: "Trinidad and Tobago",
        code: "TT",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1868",
        image: "🇹🇹",
    },
    {
        name: "Tunisia",
        code: "TN",
        timezone: "W. Central Africa Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+216",
        image: "🇹🇳",
    },
    {
        name: "Turkey",
        code: "TR",
        timezone: "Turkey Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+90",
        image: "🇹🇷",
    },
    {
        name: "Turkmenistan",
        code: "TM",
        timezone: "West Asia Standard Time",
        utc: "UTC+05:00",
        mobileCode: "+993",
        image: "🇹🇲",
    },
    {
        name: "Turks and Caicos Islands",
        code: "TC",
        timezone: "Eastern Standard Time",
        utc: "UTC-05:00",
        mobileCode: "+1649",
        image: "🇹🇨",
    },
    {
        name: "Tuvalu",
        code: "TV",
        timezone: "UTC+12",
        utc: "UTC+12:00",
        mobileCode: "+688",
        image: "🇹🇻",
    },
    {
        name: "U.S. Minor Outlying Islands",
        code: "UM",
        timezone: "UTC-11",
        utc: "UTC-11:00",
        mobileCode: "+1",
        image: "🇺🇲",
    },
    {
        name: "Uganda",
        code: "UG",
        timezone: "E. Africa Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+256",
        image: "🇺🇬",
    },
    {
        name: "Ukraine",
        code: "UA",
        timezone: "FLE Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+380",
        image: "🇺🇦",
    },
    {
        name: "United Arab Emirates",
        code: "AE",
        timezone: "Arabian Standard Time",
        utc: "UTC+04:00",
        mobileCode: "+971",
        image: "🇦🇪",
    },
    {
        name: "United Kingdom",
        code: "GB",
        timezone: "GMT Standard Time",
        utc: "UTC",
        mobileCode: "+44",
        image: "🇬🇧",
    },
    {
        name: "United States",
        code: "US",
        timezone: "Pacific Standard Time",
        utc: "UTC-08:00",
        mobileCode: "+1",
        image: "🇺🇸",
    },
    {
        name: "Uruguay",
        code: "UY",
        timezone: "Montevideo Standard Time",
        utc: "UTC-03:00",
        mobileCode: "+598",
        image: "🇺🇾",
    },
    {
        name: "Uzbekistan",
        code: "UZ",
        timezone: "West Asia Standard Time",
        utc: "UTC+05:00",
        mobileCode: "+998",
        image: "🇺🇿",
    },
    {
        name: "Vanuatu",
        code: "VU",
        timezone: "Central Pacific Standard Time",
        utc: "UTC+11:00",
        mobileCode: "+678",
        image: "🇻🇺",
    },
    {
        name: "Vatican City",
        code: "VA",
        timezone: "W. Europe Standard Time",
        utc: "UTC+01:00",
        mobileCode: "+379",
        image: "🇻🇦",
    },
    {
        name: "Vietnam",
        code: "VN",
        timezone: "SE Asia Standard Time",
        utc: "UTC+07:00",
        mobileCode: "+84",
        image: "🇻🇳",
    },
    {
        name: "Virgin Islands, U.S.",
        code: "VI",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1340",
        image: "🇻🇮",
    },
    {
        name: "Virgin Islands, British",
        code: "VG",
        timezone: "SA Western Standard Time",
        utc: "UTC-04:00",
        mobileCode: "+1284",
        image: "🇻🇬",
    },
    {
        name: "Wallis and Futuna",
        code: "WF",
        timezone: "UTC+12",
        utc: "UTC+12:00",
        mobileCode: "+681",
        image: "🇼🇫",
    },
    {
        name: "Yemen",
        code: "YE",
        timezone: "Arab Standard Time",
        utc: "UTC+03:00",
        mobileCode: "+967",
        image: "🇾🇪",
    },
    {
        name: "Zambia",
        code: "ZM",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+260",
        image: "🇿🇲",
    },
    {
        name: "Zimbabwe",
        code: "ZW",
        timezone: "South Africa Standard Time",
        utc: "UTC+02:00",
        mobileCode: "+263",
        image: "🇿🇼",
    },
];

export const documentTypeToInfo = {
    4: "gdpr",
    5: "kpis_slas",
    8: "modern_slavery",
    9: "anti_money_laundering",
    10: "esg",
    11: "social_value",
};

export const allDocumentType = {
    1: "Upload Contract",
    2: "Supplier Lead Signature",
    3: "Oprational Lead Signature",
    4: "GDPR",
    5: "KPIS",
    6: "SLAS",
    7: "Sustainability",
    8: "Modern Slavery",
    9: "Anti Money Laundering",
    10: "Esg",
    11: "Social Value",
    12: "DBS Certificate",
};

export const supplierDocuments = {
    1: "Modern Slavery",
    2: "Money Laundering",
    3: "GDPR",
    4: "Sustainability",
    5: "ESG",
    6: "Privacy Policy",
    7: "Insurance Schedule",
    8: "DBS Certificate",
    9: "ISO Certificate",
    10: "HS Certificate",
};

export const documents = {
    1: "modern_slavery",
    2: "money_laundering",
    3: "gdpr",
    4: "sustainability",
    5: "esg",
    6: "privacy_policy",
    7: "insurance_schedule",
    8: "dbs_certificate",
    9: "iso_certificate",
    10: "hs_certificate",
};

export const QTdocuments: any = {
    1: "attach_document",
    2: "general_terms_and_conditions",
    3: "sow_or_sor",
    4: "pricing_matrix",
    5: "evaluation_matrix",
    6: "business_continuity_policy",
    7: "anti_corruption_and_bribary_policy",
    8: "environmental_policy",
    9: "financial_reports",
    10: "modern_slavery_policy",
    11: "social_values",
};
export const QTdocumentsFileName: any = {
    1: "attach_document_file_name",
    2: "general_terms_and_conditions_file_name",
    3: "sow_or_sor_file_name",
    4: "pricing_matrix_file_name",
    5: "evaluation_matrix_file_name",
    6: "business_continuity_policy_file_name",
    7: "anti_corruption_and_bribary_policy_file_name",
    8: "environmental_policy_file_name",
    9: "financial_reports_file_name",
    10: "modern_slavery_policy_file_name",
    11: "social_values_file_name",
};

export const Titles = [
    {
        label: "Mr",
        value: "Mr",
    },
    {
        label: "Mrs",
        value: "Mrs",
    },
    {
        label: "Miss",
        value: "Miss",
    },
    {
        label: "Master",
        value: "Master",
    },
    {
        label: "Dr",
        value: "Dr",
    },
    {
        label: "Sir",
        value: "Sir",
    },
    {
        label: "Madam",
        value: "Madam",
    },
    {
        label: "Prefer not to say",
        value: "Prefer not to say",
    },
];

export const Pronouns = [
    {
        label: "he/him/his",
        value: "he",
    },
    {
        label: "she/her",
        value: "she",
    },
    {
        label: "they/them/their",
        value: "they",
    },
];

export const ContractData = [
    {
        label: "Contract",
        value: 1,
    },
    {
        label: "NDA",
        value: 2,
    },
    {
        label: "SOW",
        value: 3,
    },
    {
        label: "Order Form",
        value: 4,
    },
];

export const contractType: any = {
    Contract: 1,
    NDA: 2,
    SOW: 3,
    "Order From": 4,
};

export const contractTypeCopy: any = {
    1: "Contract",
    2: "NDA",
    3: "SOW",
    4: "Order From",
};

export const filterData = [
    {
        label: "All",
        value: "",
    },
    {
        label: "Missing",
        value: 2,
    },
    {
        label: "Filled",
        value: 1,
    },
];

export const reminderData = [
    {
        // id: 1,
        value: 1,
        label: "Contract Owner",
    },
    {
        // id: 2,
        value: 2,
        label: "Supplier Lead",
    },
    {
        // id: 3,
        value: 3,
        label: "Authorised Signatory",
    },
];

export const quotationTenderReminderData = [
    {
        // id: 1,
        value: 1,
        label: "Supplier Admin",
    },
    {
        // id: 2,
        value: 2,
        label: "Project Owner",
    },
    {
        // id: 3,
        value: 3,
        label: "Project Creator (Client Admin)",
    },
];

export const ContractStatusData = [
    {
        label: "Draft",
        value: 1,
    },
    {
        label: "Pending",
        value: 2,
    },
    {
        label: "Active",
        value: 3,
    },
    {
        label: "Expired",
        value: 4,
    },
    {
        label: "Terminated",
        value: 5,
    },
    {
        label: "Breached",
        value: 6,
    },
];

export const FormContractStatusData = [
    {
        label: "Draft",
        value: 1,
    },
    {
        label: "Pending",
        value: 2,
    },
    {
        label: "Active",
        value: 3,
    },
    {
        label: "Expired",
        value: 4,
    },
    {
        label: "Terminated",
        value: 5,
    },
    {
        label: "Breached",
        value: 6,
    },
];

export const FormContractStatusActiveData = [
    {
        label: "Active",
        value: 3,
    },
    {
        label: "Terminated",
        value: 5,
    },
    {
        label: "Breached",
        value: 6,
    },
];

export const CurrencyData = [
    {
        label: "£ GBP",
        value: "GBP",
    },
    {
        label: "$ DOLLAR",
        value: "DOLLAR",
    },
    {
        label: "€ EURO",
        value: "EURO",
    },
    {
        label: "₹ INR",
        value: "INR",
    },
    {
        label: "¥ YUAN",
        value: "YUAN",
    },
];

export const requestType = [
    {
        label: "New requirement",
        value: 1,
    },
    {
        label: "Renewal",
        value: 2,
    },
    {
        label: "Compliance",
        value: 3,
    },
    {
        label: "Benchmarking",
        value: 4,
    },
    {
        label: "Change Request",
        value: 5,
    },
];

export const supplierStatus = [
    {
        label: "Uncontracted Unapproved",
        value: 1,
    },
    {
        label: "Unapproved Contracted",
        value: 2,
    },
    {
        label: "Approved Contracted",
        value: 3,
    },
    {
        label: "Approved Uncontracted",
        value: 4,
    },
];

export const ProjectStatus = [
    {
        label: "New Project",
        value: 1,
    },
    {
        label: "On Hold",
        value: 2,
    },
    {
        label: "Sourcing",
        value: 3,
    },
    {
        label: "Selection",
        value: 4,
    },
    {
        label: "Signing",
        value: 5,
    },
    {
        label: "Supervision",
        value: 6,
    },
];

export const supplierStatusCopy = [
    {
        label: "Unapproved Contracted",
        value: 2,
    },
    {
        label: "Approved Contracted",
        value: 3,
    },
    {
        label: "Approved Uncontracted",
        value: 4,
    },
];

export const supplierStatusObject = {
    1: "Uncontracted Unapproved",
    2: "Unapproved Contracted",
    3: "Approved Contracted",
    4: "Approved Uncontracted",
};

export const languageData = [
    {
        label: "English",
        value: "English",
    },
    {
        label: "Spanish",
        value: "Spanish",
    },
    {
        label: "Portuguese",
        value: "Portuguese",
    },
];

export const CurrencySymbole: any = {
    GBP: "£",
    EURO: "€",
    INR: "₹",
    YUAN: "¥",
    DOLLAR: "$",
};

export const ContractTermType = [
    {
        label: "Fixed",
        value: 0,
    },
    {
        label: "Auto-Renewed",
        value: 1,
    },
];

export const ContractExpiringDays = [
    {
        label: "30 Days",
        value: 30,
    },
    {
        label: "60 Days",
        value: 60,
    },
    {
        label: "90 Days",
        value: 90,
    },
];

export const CompanyTypes = [
    {
        label: "Asian Owned",
        value: "asian_owned",
    },
    {
        label: "Black Owned",
        value: "black_owned",
    },
    {
        label: "Disabled Owned",
        value: "disabled_owned",
    },
    {
        label: "HUB",
        value: "hub",
    },
    {
        label: "LGBTQ+ Owned,",
        value: "LGBTQ+_owned,",
    },
    {
        label: "Neurodiverse Owned",
        value: "Neurodiverse_owned",
    },
    {
        label: "Other Minority Owned",
        value: "other_minority_owned",
    },
    {
        label: "Service Disabled Veteran Owned",
        value: "service_disabled_veteran_owned",
    },
    {
        label: "SME",
        value: "sme",
    },
    {
        label: "Veteran Owned",
        value: "veteran_owned",
    },
    {
        label: "Female Owned",
        value: "female_owned",
    },
    {
        label: "Social Enterprise.",
        value: "social_enterprise.",
    },
    {
        label: "Other",
        value: "other",
    },
];

export const PayGroup = [
    {
        label: "Invoice date",
        value: 1,
    },
    {
        label: "Invoice received",
        value: 2,
    },
];

export const RiskLeval = [
    {
        label: "Level 1",
        value: 1,
    },
    {
        label: "Level 2",
        value: 2,
    },
    {
        label: "Level 3",
        value: 3,
    },
    {
        label: "Level 4",
        value: 4,
    },
    {
        label: "Level 5",
        value: 5,
    },
];

export const SupplierStatus = [
    {
        label: "Approved Contracted",
        value: 3,
    },
    {
        label: "Approved Uncontracted",
        value: 4,
    },
    {
        label: "Unapproved Contracted",
        value: 2,
    },
    {
        label: "Uncontracted Unapproved",
        value: 1,
    },
];

export const keySupplierOptions = [
    {
        label: "Yes",
        value: 1,
    },
    {
        label: "No",
        value: 0,
    },
];

export const defaultFilterObject = {
    currentPage: 1,
    perPage: 10,
    searchValue: "",
    sortOrder: "",
    sortColumn: "",
    formDetails: "",
    id: 0,
    contractStartDate: "",
    contractEndDate: "",
    contractOwner: "",
    supplierLead: "",
    contractStatus: "",
    currency: "",
    contractType: "",
    category: "",
    contractValidation: "",
    myContracts: 0,
};

export const defaultResourcesFilterObject = {
    currentPage: 1,
    perPage: 10,
    searchValue: "",
    activeTab: "policy-documents",
};

export const activityType = [
    {
        label: "Single Source",
        value: 1,
    },
    {
        label: "Framework",
        value: 2,
    },
    {
        label: "Stay with incumbent",
        value: 3,
    },
    {
        label: "Request for Information (RFI)",
        value: 4,
    },
    {
        label: "Request for Quotation (RFQ)",
        value: 5,
    },
    {
        label: "Invite to Tender (ITT)",
        value: 6,
    },
];

export const requestStatus = [
    {
        label: "Awaited",
        value: 1,
    },
    {
        label: "Approved",
        value: 2,
    },
    {
        label: "Rejected",
        value: 3,
    },
    // {
    //     label: "Work in Progress",
    //     value: 4,
    // },
    // {
    //     label: "Rejected",
    //     value: 5,
    // },
];

export const QTactivityType = [
    {
        label: "Request for Quotation",
        value: 1,
    },
    {
        label: "Request for Price",
        value: 2,
    },
    {
        label: " Request for Information",
        value: 3,
    },
];

export const expectedTerms = [
    {
        label: 1,
        value: "1",
    },
    {
        label: 2,
        value: "2",
    },
    {
        label: 3,
        value: "3",
    },
    {
        label: 4,
        value: "4",
    },
    {
        label: 5,
        value: "5",
    },
    {
        label: 6,
        value: "6",
    },
    {
        label: 7,
        value: "7",
    },
    {
        label: 8,
        value: "8",
    },
    {
        label: 9,
        value: "9,",
    },
    {
        label: 10,
        value: "10",
    },

    {
        label: 11,
        value: "11",
    },
    {
        label: 12,
        value: "12",
    },
    {
        label: 13,
        value: "13",
    },
    {
        label: 14,
        value: "14",
    },
    {
        label: 15,
        value: "15",
    },

    {
        label: 16,
        value: "16",
    },
    {
        label: 17,
        value: "17",
    },
    {
        label: 18,
        value: "18",
    },
    {
        label: 19,
        value: "19",
    },
    {
        label: 20,
        value: "20",
    },
    {
        label: 21,
        value: "21",
    },
    {
        label: 22,
        value: "22",
    },
    {
        label: 23,
        value: "23",
    },
    {
        label: 24,
        value: "24",
    },
    {
        label: 36,
        value: "36",
    },
    {
        label: 48,
        value: "48",
    },
    {
        label: 60,
        value: "60",
    },
    {
        label: 72,
        value: "72",
    },
    {
        label: 84,
        value: "84",
    },
    {
        label: 96,
        value: "96",
    },
    {
        label: 108,
        value: "108",
    },
    {
        label: 120,
        value: "120",
    },
    {
        label: 132,
        value: "132",
    },
    {
        label: 144,
        value: "144",
    },
    {
        label: 156,
        value: "156",
    },
    {
        label: 168,
        value: "168",
    },
    {
        label: 180,
        value: "180",
    },
];

export const paymentTerms = [
    {
        label: 1,
        value: "1",
    },
    {
        label: 2,
        value: "2",
    },
    {
        label: 3,
        value: "3",
    },
    {
        label: 4,
        value: "4",
    },
    {
        label: 5,
        value: "5",
    },
    {
        label: 6,
        value: "6",
    },
    {
        label: 7,
        value: "7",
    },
    {
        label: 8,
        value: "8",
    },
    {
        label: 9,
        value: "9,",
    },
    {
        label: 10,
        value: "10",
    },

    {
        label: 11,
        value: "11",
    },
    {
        label: 12,
        value: "12",
    },
    {
        label: 13,
        value: "13",
    },
    {
        label: 14,
        value: "14",
    },
    {
        label: 15,
        value: "15",
    },

    {
        label: 16,
        value: "16",
    },
    {
        label: 17,
        value: "17",
    },
    {
        label: 18,
        value: "18",
    },
    {
        label: 19,
        value: "19",
    },
    {
        label: 20,
        value: "20",
    },
    {
        label: 21,
        value: "21",
    },
    {
        label: 22,
        value: "22",
    },
    {
        label: 23,
        value: "23",
    },
    {
        label: 24,
        value: "24",
    },
    {
        label: 25,
        value: "25",
    },
    {
        label: 26,
        value: "26",
    },
    {
        label: 27,
        value: "27",
    },
    {
        label: 28,
        value: "28",
    },
    {
        label: 29,
        value: "29",
    },
    {
        label: 30,
        value: "30",
    },
    {
        label: 45,
        value: "45",
    },
    {
        label: 60,
        value: "60",
    },
];

export const sidebarData = [
    {
        id: "dashboard",
        path_key: "dashboard",
        label: "Dashboard",
        locale_label: "header.dashboard",
        icon: "fa-fw fa-solid fa-grid",
        index: "1",
        link: "/dashboard",
        sideBar: true,
    },
    {
        id: "super_users",
        path_key: "super_users",
        label: "Buying Station Client Database",
        locale_label: "header.super_users",
        icon: "fa-fw fa-sharp fa-solid fa-user-secret",
        index: "2",
        link: "/super-admin",
        sideBar: true,
    },
    {
        id: "contactus_responses",
        path_key: "contactus_responses",
        label: "Contact Us Inquiries",
        locale_label: "header.contactus_responses",
        icon: "fa-fw fa-solid fa-address-card",
        index: "5",
        link: "/contact-us-responses",
        sideBar: true,
    },
    {
        id: "client_admins",
        path_key: "client_admins",
        label: "My Clients",
        locale_label: "header.client_admins",
        icon: "fa-fw fa-solid fa-user-shield",
        index: "6",
        link: "/client-admins",
        sideBar: true,
    },
    {
        id: "client_managers",
        path_key: "client_managers",
        label: "Client Account Managers",
        locale_label: "header.client_managers",
        icon: "fa-fw fa-solid fa-user-gear",
        index: "7",
        link: "/client-managers",
        sideBar: true,
    },
    {
        id: "client_users",
        path_key: "client_users",
        label: "Users",
        locale_label: "header.client_users",
        icon: "fa-fw fa-solid fa-user-tie",
        index: "8",
        link: "/client-users",
        sideBar: true,
    },
    {
        id: "suppliers",
        path_key: "suppliers",
        label: "Supplier",
        locale_label: "header.suppliers",
        icon: "fa-solid fa-truck-arrow-right",
        index: "9",
        link: "/supplier-admins",
        sideBar: true,
    },

    {
        id: "contracts",
        path_key: "contracts",
        label: "Contracts",
        locale_label: "header.contracts",
        icon: "fa-solid fa-file-contract",
        index: "10",
        link: "/contracts",
        sideBar: true,
        // children: []
        // children: [
        //   {
        //     id: "contracts",
        //     path_key: "/contracts",
        //     label: "Contracts Dashboard",
        //     icon: "fa-fw fa-solid fa-user-tie",
        //     index: "10-1",
        //     link: "/contracts",
        //     sideBar: true,
        //   },
        //   {
        //     id: "reporting",
        //     path_key: "reporting",
        //     label: "Reporting",
        //     icon: "fa-fw fa-solid fa-user-tie",
        //     index: "10-2",
        //     link: "/reporting",
        //     sideBar: true,
        //     disable: true,
        //   },
        //   {
        //     id: "myprojects",
        //     path_key: "myprojects",
        //     label: "My Projects",
        //     icon: "fa-fw fa-solid fa-user-tie",
        //     index: "10-3",
        //     link: "/myprojects",
        //     sideBar: true,
        //     disable: true,
        //   },
        // ],
    },
    {
        id: "supplier_users",
        path_key: "supplier-user",
        label: "Supplier Users",
        locale_label: "header.supplier_users",
        icon: "fa-solid fa-truck-arrow-right",
        index: "12",
        link: "/supplier-users",
        sideBar: true,
    },
    {
        id: "project_pipeline",
        path_key: "project_pipeline",
        label: "Project Pipeline",
        locale_label: "header.project_pipeline",
        icon: "fa-solid fa-rectangle-vertical-history",
        index: "14",
        link: "/project-pipeline",
        sideBar: true,
        children: [
            {
                id: "requests",
                path_key: "/requests",
                label: "Requests",
                locale_label: "header.requests",
                icon: "fa-solid fa-file-signature",
                index: "14-1",
                link: "/project-pipeline/requests",
                sideBar: true,
            },
            {
                id: "projects",
                path_key: "projects",
                label: "Projects",
                locale_label: "header.projects",
                icon: "fa-solid fa-file-contract",
                index: "14-2",
                link: "/project-pipeline/projects",
                sideBar: true,
            },
        ],
    },
    {
        id: "roles-permissions",
        path_key: "roles-permissions",
        label: "Roles And Permissions",
        locale_label: "header.roles_and_permissions",
        icon: "fa-solid fa-user-unlock",
        index: "15",
        link: "/roles-permissions",
        sideBar: true,
    },
    {
        id: "supplier_directory",
        path_key: "supplier_directory",
        label: "Supplier Directory",
        locale_label: "header.supplier_directory",
        icon: "fa-solid fa-address-book",
        index: "16",
        link: "/supplier-directory",
        sideBar: true,
    },
    {
        id: "resources",
        path_key: "resources",
        label: "Resources",
        locale_label: "header.resources",
        icon: "fa-solid fa-gears",
        index: "17",
        link: "/resources",
        sideBar: true,
    },
    {
        id: "quotations_tender",
        path_key: "quotations_tender",
        label: "Quotations & Tender",
        locale_label: "header.quotations_tender",
        icon: "fa-solid fa-file-invoice-dollar",
        index: "18",
        link: "/quotations-tender",
        sideBar: true,
    },
    {
        id: "settings",
        path_key: "settings",
        label: "Setting",
        locale_label: "header.settings",
        icon: "fa-solid fa-gear",
        index: "14",
        link: "/Setting",
        sideBar: true,
        children: [
            {
                id: "prefix",
                path_key: "/prefix",
                label: "Prefix",
                locale_label: "header.prefix",
                icon: "fa-solid fa-file-signature",
                index: "14-1",
                link: "/settings/prefix",
                sideBar: true,
            },
        ],
    },
    {
        id: "supplier_quotations_tender",
        path_key: "supplier_quotations_tender",
        label: "My Quotations & Tender",
        locale_label: "header.supplier_quotations_tender",
        icon: "fa-solid fa-file-invoice-dollar",
        index: "19",
        link: "/quotations-tender/supplier-q-t",
        sideBar: true,
    },
    {
        id: "signing_entity",
        path_key: "signing_entity",
        label: "Signing Entity",
        locale_label: "header.signing_entity",
        icon: "fa-solid fa-right-to-bracket",
        index: "20",
        link: "/signing-entity",
        sideBar: true,
    },
];

export const nonSidebarData = [
    {
        id: "profile",
        path_key: "profile",
        label: "Profile",
        icon: "icon-menu",
        link: "/profile",
        index: "3",
    },
    {
        id: "changepassword",
        path_key: "changepassword",
        label: "Change Password",
        icon: "icon-menu",
        link: "/change-password",
        index: "4",
    },
    {
        id: "my_company",
        path_key: "my_company",
        label: "My Company",
        icon: "icon-menu",
        link: "/my-company",
        index: "11",
    },

    {
        id: "default_password_change",
        path_key: "default_password_change",
        label: "Default Password Change",
        icon: "fa-solid fa-truck-arrow-right",
        index: "13",
        link: "/supplier-users",
        sideBar: true,
    },

    {
        id: "privacy_policy",
        path_key: "privacy_policy",
        label: "Privacy Policy",
        icon: "fa-solid fa-truck-arrow-right",
        index: "21",
        link: "/privacy_policy",
        sideBar: true,
    },
];

export const suppliersAdminTabOptions = [
    {
        label: "Primary Details",
        value: "primary-details",
    },
    {
        label: "Compliance Due Diligence",
        value: "compliance-due-diligence",
    },
    {
        label: "Reference",
        value: "reference",
    },
    {
        label: "Supporting Documents",
        value: "supporting-documents",
    },
];

export const contractsTabOptions = [
    {
        label: "Primary Details",
        value: "primary-details",
    },
    {
        label: "Upload Contract",
        value: "upload-contract",
    },
    {
        label: "Signatory Details",
        value: "signatory-details",
    },
    {
        label: "Supporting Documents",
        value: "supporting-documents",
    },
    {
        label: "Additional Information",
        value: "additional-information",
    },
];

export const inputTypeOptions = [
    {
        label: "Text",
        value: "text",
    },
    {
        label: "Textarea",
        value: "textarea",
    },
    {
        label: "Radio",
        value: "radio",
    },
    {
        label: "Checkbox",
        value: "checkbox",
    },
    {
        label: "Dropdown",
        value: "dropdown",
    },
    {
        label: "Date",
        value: "date",
    },
    {
        label: "Time",
        value: "time",
    },
    {
        label: "Date Time",
        value: "date-time",
    },
    {
        label: "File",
        value: "file",
    },
];

export const fileExtensionType = [
    {
        label: "DOC",
        value: "doc",
    },
    {
        label: "DOCX",
        value: "docx",
    },
    {
        label: "PDF",
        value: "pdf",
    },
    {
        label: "TXT",
        value: "txt",
    },
    {
        label: "RTF",
        value: "rtf",
    },
    {
        label: "ODT",
        value: "odt",
    },
    {
        label: "XLS",
        value: "xls",
    },
    {
        label: "XLSX",
        value: "xlsx",
    },
    {
        label: "CSV",
        value: "csv",
    },
    {
        label: "PPT",
        value: "ppt",
    },
    {
        label: "PPTX",
        value: "pptx",
    },
    {
        label: "JPG",
        value: "jpg",
    },
    {
        label: "JPEG",
        value: "jpeg",
    },
    {
        label: "PNG",
        value: "png",
    },
];

export const months = {
    "01": "Jan",
    "02": "Feb",
    "03": "Mar",
    "04": "Apr",
    "05": "May",
    "06": "Jun",
    "07": "Jul",
    "08": "Aug",
    "09": "Sep",
    "10": "Oct",
    "11": "Nov",
    "12": "Dec",
};
